<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-3L9UGKR" name="org.sample.Datapro" tests="10" failures="0" timestamp="23 Apr 2021 04:38:37 GMT" time="11.226" errors="1">
  <testcase name="login" time="0.742" classname="org.sample.Datapro"/>
  <testcase name="login" time="4.445" classname="org.sample.Datapro"/>
  <testcase name="login" time="0.609" classname="org.sample.Datapro"/>
  <testcase name="login" time="0.721" classname="org.sample.Datapro"/>
  <testcase name="login" time="0.695" classname="org.sample.Datapro"/>
  <testcase name="login" time="0.698" classname="org.sample.Datapro"/>
  <testcase name="afterClass" time="0.000" classname="org.sample.Datapro">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at org.sample.Datapro.afterClass(Datapro.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- afterClass -->
  <testcase name="login" time="0.768" classname="org.sample.Datapro"/>
  <testcase name="login" time="0.960" classname="org.sample.Datapro"/>
  <testcase name="login" time="1.588" classname="org.sample.Datapro"/>
</testsuite> <!-- org.sample.Datapro -->
